### ISSUE TITLE
invalid hook

### ISSUE THREAD

**Issue by smooJitter** [LauraBeatris/use-selected-items-hook#4]
I am getting an 

Error: Invalid hook call.  Hooks can only be called inside of the body of a function component.

Definitely using functional components.  In fact, the functional component contains other hooks that work fine.

**Comment by LauraBeatris** [comment]
Can you please send a reproducible example? Maybe on [CodeSandbox](https://codesandbox.io/dashboard/home?workspace=b74ef2d4-8ccc-4d3a-8f89-3035553ce89f) would be good 😊

**Comment by LauraBeatris** [comment]
Will be fixed on #6

**Comment by LauraBeatris** [comment]
The issue here is that there are two different versions of `react` on the same tree. One from the hook and another from your application.

The ``react`` package should be a peer dependency in order to not be bundled.

https://github.com/LauraBeatris/use-selected-items-hook/blob/5ffcab58cf24869a0244b082aa488d24e066aa80/use-selected-items-hook/package.json#L30-L33

**Comment by LauraBeatris** [comment]
Refer to: https://en.reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by LauraBeatris** [comment]
Fixed on https://github.com/LauraBeatris/use-selected-items-hook/releases/tag/1.1.9
